### ISSUE TITLE
How to INIT in Windows?

### ISSUE THREAD

**Issue by seanvree** [radiac/caman#9]
I'm not new to windows, nor Git or Python,

I've cloned the REPO, configured the CNF files, but I'm confused about step 4:

cd caman
./caman init

how do I initialize in windows?  

I've tried with python/pip, and some other tools, but I guess I'm missing something?

Thanks,

**Comment by radiac** [comment]
Unfortunately it's a bash script, intended for use on linux. There's apparently a new way to run bash scripts on windows which might help ([this](http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/) was the top google result), but I haven't tried it myself.

Although I have no plans to support windows, if you do have any luck getting it running on there please do reply to this issue with what you did to get it working, in case anyone else wants to try in the future!

Thanks and good luck :)

**Comment by seanvree** [comment]
yeah, I just saw the comments about windows in your readme, so I thought I was missing something. I'm familiar with BASH in windows, use it all the time.  Doesn't work tho with this script. 

Thanks for the reply!
